---
name: "Auto-Organiser"
guid: "5D5FAFD8-886C-442C-ADE9-7B5E39F908BD"
version: "10.9.10.0"
targetAbi: "10.9.10.0"
framework: "net8.0"
overview: "Automatically organise and rename files"
description: >
  This plugin automatically organises and renames files as recommended by Jellyfin.
category: "File Organiser"
owner: "geo-martino"
artifacts:
- "Jellyfin.Plugin.AutoOrganiser.dll"
changelog: >
  changelog
