---
name: "Template"
guid: "5D5FAFD8-886C-442C-ADE9-7B5E39F908BD"
version: "10.9.10.0"
targetAbi: "10.9.10.0"
framework: "net8.0"
overview: "Sorts and renames movie files"
description: >
  This plugin automatically sorts and renames movie files as recommended by Jellyfin.
category: "File Sorter"
owner: "geo-martino"
artifacts:
- "Jellyfin.Plugin.MovieFileSorter.dll"
changelog: >
  changelog
